### PR TITLE
Add other necessary changes for dark mode

### PR DESCRIPTION
**Pull request by MahdiRahmany**
just add some feature that theme depend's on client system theme

### CODE REVIEW

**Comment by MahdiRahmany** [comment]
Add other necessary changes for dark mode.

**Comment by MahdiRahmany** [comment]
1

**Comment by mo271** [comment]
Thanks for the the pull request. 

Unfortunately the dark mode with those changes look totally unreadable:
darkmode
When you want to test it, click on "I'm Feeling Lucky" and see if it still looks ok!

**Review by mo271 — CHANGES_REQUESTED** [review]
see comment in pull request

**Comment by mo271** [comment]
Thanks, that looks already better!
darkmode2


Three problems remain:

1.  the favicon icon is not readable
2. the github image at the bottom right of the page is not readable (this is an svg, so it should be possible to adapt it easily without having a second asset
3. the color of the links is a shade of blue that is to dark, there is not enough contrast to read it clearly

**Review by mo271 — APPROVED** [review]

**Comment by mo271** [comment]
Thanks! 
I also added the dark mode for the favicon, now I think it looks ok!

**Comment by MahdiRahmany** [comment]
Thank you. This was my first pr and it was exciting to be able to contribute to a repository. Of course, the UI of the site can be improved

**Pull request merged**
